# Generated by Django 2.0.6 on 2019-10-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarageSellModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerName', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('datePurchased', models.DateTimeField()),
            ],
        ),
    ]
